/* WARNING: This file is auto-generated . Do not edit manually. */

export type BillingPaymentMeanEnum =
  | 'cash'
  | 'chargeback'
  | 'check'
  | 'cheque'
  | 'creditAccount'
  | 'creditCard'
  | 'debtAccount'
  | 'deposit'
  | 'digitalLaunchPad'
  | 'edinar'
  | 'fidelityPoints'
  | 'free'
  | 'ideal'
  | 'incubatorAccount'
  | 'mandat'
  | 'multibanco'
  | 'none'
  | 'ovhAccount'
  | 'paymentMandate'
  | 'paypal'
  | 'payu'
  | 'platnosci'
  | 'refund'
  | 'rupay'
  | 'transfer'
  | 'withdrawal';
