/* WARNING: This file is auto-generated . Do not edit manually. */

export type CloudInstanceInstanceStatusEnum =
  | 'ACTIVE'
  | 'BUILD'
  | 'BUILDING'
  | 'DELETED'
  | 'DELETING'
  | 'ERROR'
  | 'HARD_REBOOT'
  | 'MIGRATING'
  | 'PASSWORD'
  | 'PAUSED'
  | 'REBOOT'
  | 'REBUILD'
  | 'RESCUE'
  | 'RESCUED'
  | 'RESCUING'
  | 'RESIZE'
  | 'RESIZED'
  | 'RESUMING'
  | 'REVERT_RESIZE'
  | 'SHELVED'
  | 'SHELVED_OFFLOADED'
  | 'SHELVING'
  | 'SHUTOFF'
  | 'SNAPSHOTTING'
  | 'SOFT_DELETED'
  | 'STOPPED'
  | 'SUSPENDED'
  | 'UNKNOWN'
  | 'UNRESCUING'
  | 'UNSHELVING'
  | 'VERIFY_RESIZE';
