/* WARNING: This file is auto-generated . Do not edit manually. */

export type DbaasLogsUrlTypeEnum =
  | 'CONSOLE'
  | 'ELASTICSEARCH_API'
  | 'GRAYLOG_API'
  | 'GRAYLOG_WEBUI'
  | 'HTTP_GELF'
  | 'HTTP_TLS_GELF'
  | 'KIBANA_WEBUI'
  | 'OPENSEARCH_API'
  | 'OSD_WEBUI'
  | 'SERVICE_DOMAIN'
  | 'TCP_BEATS'
  | 'TCP_CAP_N_PROTO'
  | 'TCP_GELF'
  | 'TCP_LTSV_LINE'
  | 'TCP_LTSV_NUL'
  | 'TCP_RFC5424'
  | 'TCP_TLS_BEATS'
  | 'TCP_TLS_CAP_N_PROTO'
  | 'TCP_TLS_GELF'
  | 'TCP_TLS_LTSV_LINE'
  | 'TCP_TLS_LTSV_NUL'
  | 'TCP_TLS_RFC5424'
  | 'UDP_CAP_N_PROTO'
  | 'UDP_GELF'
  | 'UDP_LTSV_LINE'
  | 'UDP_LTSV_NUL'
  | 'UDP_RFC5424'
  | 'WEB_SOCKET';
