/* WARNING: This file is auto-generated . Do not edit manually. */

export type DedicatedTemplateOsSubfamilyEnum =
  | 'alma'
  | 'aos'
  | 'arch'
  | 'centos'
  | 'cloudlinux'
  | 'coreos'
  | 'debian'
  | 'dgx'
  | 'esxi'
  | 'fedora'
  | 'freebsd'
  | 'gentoo'
  | 'hyperv'
  | 'omnios'
  | 'openio'
  | 'openmediavault'
  | 'opensuse'
  | 'ovh'
  | 'pcs'
  | 'power'
  | 'proxmox'
  | 'rhel'
  | 'rocky'
  | 'slackware'
  | 'sles-sap'
  | 'smartos'
  | 'solusvm'
  | 'ubuntu'
  | 'windows-server-core'
  | 'windows-server-desktop-exp'
  | 'xcp'
  | 'xen';
