/* WARNING: This file is auto-generated . Do not edit manually. */

export type DedicatedAnthosBaremetalStatusEnum =
  | 'BAREMETAL_STATUS_AVAILABLE'
  | 'BAREMETAL_STATUS_DELIVERING'
  | 'BAREMETAL_STATUS_IN_MAINTENANCE'
  | 'BAREMETAL_STATUS_IN_USE'
  | 'BAREMETAL_STATUS_RESTARTING'
  | 'BAREMETAL_STATUS_SUPPRESSING'
  | 'BAREMETAL_STATUS_UNSPECIFIED';
