/* WARNING: This file is auto-generated . Do not edit manually. */

export type DedicatedAnthosStorageVMStateEnum =
  | 'STORAGE_VMSTATE_DELETING'
  | 'STORAGE_VMSTATE_INITIALIZING'
  | 'STORAGE_VMSTATE_RUNNING'
  | 'STORAGE_VMSTATE_STARTING'
  | 'STORAGE_VMSTATE_STOPPED'
  | 'STORAGE_VMSTATE_STOPPING'
  | 'STORAGE_VMSTATE_UNSPECIFIED';
