/* WARNING: This file is auto-generated . Do not edit manually. */

export type DomainOperationFunctionEnum =
  | 'ContactControl'
  | 'DnsAnycastActivate'
  | 'DnsAnycastDeactivate'
  | 'DnssecDisable'
  | 'DnssecEnable'
  | 'DnssecResigning'
  | 'DnssecRollKsk'
  | 'DnssecRollZsk'
  | 'DomainAfterMarket'
  | 'DomainContactControl'
  | 'DomainContactUpdate'
  | 'DomainControl'
  | 'DomainCreate'
  | 'DomainDelete'
  | 'DomainDnsUpdate'
  | 'DomainDsUpdate'
  | 'DomainEmailRedirectionsCreate'
  | 'DomainEmailRedirectionsDelete'
  | 'DomainHold'
  | 'DomainHostCreate'
  | 'DomainHostDelete'
  | 'DomainHostUpdate'
  | 'DomainIncomingTransfer'
  | 'DomainLock'
  | 'DomainOutgoingTransfer'
  | 'DomainRegistryDelete'
  | 'DomainRenew'
  | 'DomainResourceDelete'
  | 'DomainRestore'
  | 'DomainTrade'
  | 'DomainUnhold'
  | 'DomainUnlock'
  | 'ZoneImport';
