/* WARNING: This file is auto-generated . Do not edit manually. */

import { DomainExtensionsRegistryConfigurationsTransferLifecycleRegistryConfiguration } from './DomainExtensionsRegistryConfigurationsTransferLifecycleRegistryConfiguration';
import { DomainExtensionsRegistryConfigurationsRestoreLifecycleRegistryConfiguration } from './DomainExtensionsRegistryConfigurationsRestoreLifecycleRegistryConfiguration';
import { DomainExtensionsRegistryConfigurationsCreateLifecycleRegistryConfiguration } from './DomainExtensionsRegistryConfigurationsCreateLifecycleRegistryConfiguration';
import { DomainExtensionsRegistryConfigurationsOrderLifecycleRegistryConfiguration } from './DomainExtensionsRegistryConfigurationsOrderLifecycleRegistryConfiguration';
import { DomainExtensionsRegistryConfigurationsRenewLifecycleRegistryConfiguration } from './DomainExtensionsRegistryConfigurationsRenewLifecycleRegistryConfiguration';

export type DomainExtensionsRegistryConfigurationsLifecycleRegistryConfiguration = {
  create: DomainExtensionsRegistryConfigurationsCreateLifecycleRegistryConfiguration;
  order: DomainExtensionsRegistryConfigurationsOrderLifecycleRegistryConfiguration;
  renew: DomainExtensionsRegistryConfigurationsRenewLifecycleRegistryConfiguration;
  restore: DomainExtensionsRegistryConfigurationsRestoreLifecycleRegistryConfiguration;
  transfer: DomainExtensionsRegistryConfigurationsTransferLifecycleRegistryConfiguration;
};
