/* WARNING: This file is auto-generated . Do not edit manually. */

import { DomainExtensionsRegistryConfigurationsCreateLifecycleRegistryConfiguration } from './DomainExtensionsRegistryConfigurationsCreateLifecycleRegistryConfiguration';
import { DomainExtensionsRegistryConfigurationsTransferLifecycleRegistryConfiguration } from './DomainExtensionsRegistryConfigurationsTransferLifecycleRegistryConfiguration';
import { DomainExtensionsRegistryConfigurationsRestoreLifecycleRegistryConfiguration } from './DomainExtensionsRegistryConfigurationsRestoreLifecycleRegistryConfiguration';
import { DomainExtensionsRegistryConfigurationsRenewLifecycleRegistryConfiguration } from './DomainExtensionsRegistryConfigurationsRenewLifecycleRegistryConfiguration';
import { DomainExtensionsRegistryConfigurationsOrderLifecycleRegistryConfiguration } from './DomainExtensionsRegistryConfigurationsOrderLifecycleRegistryConfiguration';

export type DomainExtensionsRegistryConfigurationsLifecycleRegistryConfiguration = {
  create?: DomainExtensionsRegistryConfigurationsCreateLifecycleRegistryConfiguration;
  order?: DomainExtensionsRegistryConfigurationsOrderLifecycleRegistryConfiguration;
  renew?: DomainExtensionsRegistryConfigurationsRenewLifecycleRegistryConfiguration;
  restore?: DomainExtensionsRegistryConfigurationsRestoreLifecycleRegistryConfiguration;
  transfer?: DomainExtensionsRegistryConfigurationsTransferLifecycleRegistryConfiguration;
};
