/* WARNING: This file is auto-generated . Do not edit manually. */

export type EmailDomainMigrationCheckCodeEnum =
  | 'ACCOUNT_EMPTY'
  | 'ACCOUNT_INPROGRESS'
  | 'DELEGATION_EXIST'
  | 'DOMAIN_EMPTY'
  | 'FILTER_EXIST'
  | 'FORWARD_EXIST'
  | 'FORWARD_LOCAL'
  | 'MAILINGLIST_EXIST'
  | 'MAILINGLIST_INPROGRESS'
  | 'MAILPROXY_BAD_INFRA'
  | 'MAILPROXY_EMPTY'
  | 'MAILPROXY_INPROGRESS'
  | 'MAILPROXY_RESERVATION'
  | 'REDIRECTION_INPROGRESS'
  | 'RESPONDER_EXIST'
  | 'RESPONDER_INPROGRESS'
  | 'UNKNOW';
