/* WARNING: This file is auto-generated . Do not edit manually. */

import { EmailExchangeRenewPeriodEnum } from './EmailExchangeRenewPeriodEnum';
import { EmailExchangeObjectStateEnum } from './EmailExchangeObjectStateEnum';
import { EmailExchangeOvhLicenceEnum } from './EmailExchangeOvhLicenceEnum';
import { EmailExchangeCountryCodeEnum } from './EmailExchangeCountryCodeEnum';
import { EmailExchangeSpamAndVirusConfiguration } from './EmailExchangeSpamAndVirusConfiguration';
import { EmailExchangeMailingFilterEnum } from './EmailExchangeMailingFilterEnum';

export type EmailExchangeAccount = {
  SAMAccountName: string | null;
  accountLicense: EmailExchangeOvhLicenceEnum;
  city: string | null;
  company: string | null;
  configured: boolean;
  countryCode: EmailExchangeCountryCodeEnum | null;
  creationDate: Date | null;
  currentUsage: number | null;
  customIsolationId: number | null;
  deleteAtExpiration: boolean | null;
  deleteOutlookAtExpiration: boolean | null;
  description: string | null;
  displayName: string | null;
  domain: string;
  exchangeGuid: string | null;
  expirationDate: Date | null;
  expirationOutlookDate: Date | null;
  fax: string | null;
  firstName: string | null;
  forwardingEmail: string | null;
  guid: string | null;
  hiddenFromGAL: boolean;
  id: number;
  initial: string | null;
  jobDepartment: string | null;
  jobTitle: string | null;
  lastLogoffDate: Date | null;
  lastLogonDate: Date | null;
  lastName: string | null;
  lastUpdateDate: Date | null;
  litigation: boolean;
  litigationPeriod: number | null;
  login: string;
  mailSenderDisplay: string | null;
  mailingFilter: EmailExchangeMailingFilterEnum[] | null;
  mobile: string | null;
  numberOfAliases: number;
  office: string | null;
  outlookLicense: boolean;
  owaLimited: boolean;
  passwordLastUpdate: Date | null;
  phone: string | null;
  postalCode: string | null;
  primaryEmailAddress: string;
  quota: number;
  region: string | null;
  renewOutlookPeriod: EmailExchangeRenewPeriodEnum | null;
  renewPeriod: EmailExchangeRenewPeriodEnum | null;
  sbrDestination: string | null;
  sendConnectorId: number | null;
  spamAndVirusConfiguration: EmailExchangeSpamAndVirusConfiguration;
  spamDetected: boolean;
  spamTicketNumber: number | null;
  state: EmailExchangeObjectStateEnum;
  storeCopyOfEmail: boolean;
  streetAddress: string | null;
  taskPendingId: number | null;
};
