/* WARNING: This file is auto-generated . Do not edit manually. */

export type HostingWebLocalSeoFlowStatusEnum =
  | 'ALL_INFORMATION_SUBMITTED'
  | 'DONT_REMOVE'
  | 'INACTIVE'
  | 'MANUALLY_DEACTIVATED'
  | 'NEEDS_REVIEW'
  | 'NOT_SUPPORTED'
  | 'NO_ACTION_NEEDED'
  | 'REMOVAL_NEEDED'
  | 'REMOVAL_REVIEW_NEEDED'
  | 'REMOVAL_SUBMITTED'
  | 'REMOVED'
  | 'SUBMISSION_NEEDED'
  | 'WAITING_DIRECTORY_ACTION'
  | 'WAITING_USER_ACTION';
