/* WARNING: This file is auto-generated . Do not edit manually. */

export type HostingWebLanguagesEnum =
  | 'node10'
  | 'node11'
  | 'node12'
  | 'node14'
  | 'node8'
  | 'node9'
  | 'other'
  | 'php4'
  | 'php5.2'
  | 'php5.3'
  | 'php5.4'
  | 'php5.5'
  | 'php5.6'
  | 'php7.0'
  | 'php7.1'
  | 'php7.2'
  | 'php7.3'
  | 'php7.4'
  | 'php8.0'
  | 'php8.1'
  | 'php8.2'
  | 'python2'
  | 'python3'
  | 'ruby2.6';
