/* WARNING: This file is auto-generated . Do not edit manually. */

export type MsServicesTaskFunctionEnum =
  | 'activateADSync'
  | 'activateSharepoint'
  | 'addADAccount'
  | 'addADOU'
  | 'addADSyncAccount'
  | 'addADUPNSuffix'
  | 'alterMfaOnAllUsers'
  | 'changeADPassword'
  | 'changeADSyncPassword'
  | 'deactivateADSync'
  | 'delADOU'
  | 'deleteADAccount'
  | 'deleteADSyncAccount'
  | 'deleteADUPNSuffix'
  | 'disableADAccountMfa'
  | 'disableADAccountMfaTemporary'
  | 'enableADAccountMfa'
  | 'enableADSyncAccount'
  | 'generateADSyncClientUrl'
  | 'resetADAccountMfa'
  | 'setADAccount'
  | 'setPasswordPolicy';
