/* WARNING: This file is auto-generated . Do not edit manually. */

export type PackXdslServiceNameEnum =
  | 'domain'
  | 'emailPro'
  | 'exchangeAccount'
  | 'exchangeIndividual'
  | 'exchangeOrganization'
  | 'grt10ho'
  | 'grt20m10ho'
  | 'grt20m4ho'
  | 'grt4ho'
  | 'grt5m10ho'
  | 'grt5m4ho'
  | 'grtAlt'
  | 'grtDsp'
  | 'grtFt'
  | 'grtKosc'
  | 'grtOvh'
  | 'hostedEmail'
  | 'modem'
  | 'overTheBoxHardware'
  | 'overTheBoxService'
  | 'voipAlias'
  | 'voipBillingAccount'
  | 'voipEcoFax'
  | 'voipLine'
  | 'voipTrunk'
  | 'xdslAccess';
