/* WARNING: This file is auto-generated . Do not edit manually. */

export type ServiceTerminationReasonEnum =
  | 'FEATURES_DONT_SUIT_ME'
  | 'LACK_OF_PERFORMANCES'
  | 'MIGRATED_TO_ANOTHER_OVH_PRODUCT'
  | 'MIGRATED_TO_COMPETITOR'
  | 'NOT_ENOUGH_RECOGNITION'
  | 'NOT_NEEDED_ANYMORE'
  | 'NOT_RELIABLE'
  | 'NO_ANSWER'
  | 'OTHER'
  | 'PRODUCT_DIMENSION_DONT_SUIT_ME'
  | 'PRODUCT_TOOLS_DONT_SUIT_ME'
  | 'TOO_EXPENSIVE'
  | 'TOO_HARD_TO_USE'
  | 'UNSATIFIED_BY_CUSTOMER_SUPPORT';
