/* WARNING: This file is auto-generated . Do not edit manually. */

export type StartupRelatedTechnologyEnum =
  | '3dPrinting'
  | 'API'
  | 'ArtificialIntelligence'
  | 'AugmentedReality'
  | 'BankingDataInfrastructure'
  | 'Big_Data'
  | 'Blockchain'
  | 'CRM_ERP'
  | 'Chatbot'
  | 'CloudGaming'
  | 'ContainersDockers'
  | 'CyberSecurity'
  | 'Drones'
  | 'ElearningPlatform'
  | 'GeoLocalization'
  | 'Healthcareinfrastructure'
  | 'IoT'
  | 'MachineLearningDeepLearning'
  | 'Marketplace'
  | 'MobileApplications'
  | 'Orchestration'
  | 'Other'
  | 'PredictiveAnalyticAlgorithms'
  | 'Robotics'
  | 'ScientificComputation'
  | 'Storage'
  | 'Streaming'
  | 'VirtualDesktop'
  | 'VirtualMachines'
  | 'VoIP';
