/* WARNING: This file is auto-generated . Do not edit manually. */

export type StartupRelatedIndustryEnum =
  | 'AI_Wholesale'
  | 'ARTISANAT'
  | 'ASP_SI_ITServices'
  | 'Accommodation_and_FoodServices'
  | 'Agriculture'
  | 'Agro_industry'
  | 'Art_Sport_Entertainment'
  | 'Automotive'
  | 'Banking'
  | 'Construction_and_Architecture'
  | 'Databases_Wholesale'
  | 'DigitalServices'
  | 'E_Retail'
  | 'EducationalServices'
  | 'Energy_and_Water'
  | 'Game_Wholesale'
  | 'HeadOffice'
  | 'Healthcare'
  | 'Host_the_Hoster_Wholesale'
  | 'Human_Resources'
  | 'IAASproviders_WebHosters_Data'
  | 'Life_Sciences'
  | 'Manufacturing_Industry'
  | 'Mining_Industry'
  | 'NonProfit'
  | 'Other_Services_Business'
  | 'Other_Services_Personal'
  | 'Others'
  | 'PublicSector'
  | 'Real_Estate'
  | 'Retail_and_Trade'
  | 'ScienceR&D'
  | 'Software Editors'
  | 'Storage_Wholesale'
  | 'TV_Media'
  | 'Telecommunication_Internet'
  | 'Transportation_Logistics'
  | 'Ventures_for_Good'
  | 'Virtualization_Wholesale'
  | 'WebAgencies';
