/* WARNING: This file is auto-generated . Do not edit manually. */

export type StorageNetAppShareStatusEnum =
  | 'available'
  | 'creating'
  | 'creating_from_snapshot'
  | 'deleted'
  | 'deleting'
  | 'error'
  | 'error_deleting'
  | 'extending'
  | 'extending_error'
  | 'inactive'
  | 'manage_error'
  | 'manage_starting'
  | 'migrating'
  | 'migrating_to'
  | 'replication_change'
  | 'reverting'
  | 'reverting_error'
  | 'shrinking'
  | 'shrinking_error'
  | 'shrinking_possible_data_loss_error'
  | 'unmanage_error'
  | 'unmanage_starting'
  | 'unmanaged';
