/* WARNING: This file is auto-generated . Do not edit manually. */

export type VpsTaskTypeEnum =
  | 'addVeeamBackupJob'
  | 'changeRootPassword'
  | 'createSnapshot'
  | 'deleteSnapshot'
  | 'deliverVm'
  | 'getConsoleUrl'
  | 'internalTask'
  | 'migrate'
  | 'openConsoleAccess'
  | 'provisioningAdditionalIp'
  | 'reOpenVm'
  | 'rebootVm'
  | 'reinstallVm'
  | 'removeVeeamBackup'
  | 'rescheduleAutoBackup'
  | 'restoreFullVeeamBackup'
  | 'restoreVeeamBackup'
  | 'restoreVm'
  | 'revertSnapshot'
  | 'setMonitoring'
  | 'setNetboot'
  | 'startVm'
  | 'stopVm'
  | 'upgradeVm';
