/* WARNING: This file is auto-generated . Do not edit manually. */

export type XanderContactFieldEnum =
  | 'address.city'
  | 'address.country'
  | 'address.line1'
  | 'address.line2'
  | 'address.line3'
  | 'address.otherDetails'
  | 'address.province'
  | 'address.zip'
  | 'birthCity'
  | 'birthCountry'
  | 'birthDay'
  | 'birthZip'
  | 'cellPhone'
  | 'companyNationalIdentificationNumber'
  | 'email'
  | 'fax'
  | 'firstName'
  | 'gender'
  | 'language'
  | 'lastName'
  | 'legalForm'
  | 'nationalIdentificationNumber'
  | 'nationality'
  | 'organisationName'
  | 'organisationType'
  | 'phone'
  | 'spareEmail'
  | 'vat';
