/* WARNING: This file is auto-generated . Do not edit manually. */

export type XdslLineDiagnosticQuestionsEnum =
  | 'bandwidthTestUnit'
  | 'comment'
  | 'conditionsAccepted'
  | 'contactPhone'
  | 'datetimeOfAppearance'
  | 'downloadBandwidthTest'
  | 'endAfternoonHours'
  | 'endMorningHours'
  | 'followBySms'
  | 'hasModemKeptSynchronization'
  | 'idAppointment'
  | 'individualSite'
  | 'modemIsSynchronized'
  | 'modemMac'
  | 'modemStillSynchronized'
  | 'modemType'
  | 'ovhTicket'
  | 'problemType'
  | 'resolvedAfterTests'
  | 'secureSite'
  | 'severalInternetConnections'
  | 'siteClosedDays'
  | 'siteDigicode'
  | 'siteOpening'
  | 'startAfternoonHours'
  | 'startMorningHours'
  | 'uploadBandwidthTest';
